### ISSUE TITLE
Ensure support for Python 3.12

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/wayback#123]
This package mostly works for Python 3.12 (testing with 3.12.0rc2, which [Python Core expects to be the final release candidate](https://pythoninsider.blogspot.com/2023/09/python-3120-release-candidate-2-now.html)), but has some tooling issues:
- [x] Versioneer does not work (#122)
- [x] Flake8 does not work (they added support in v6.1.0 which is a major release ahead of where we are) (#124)
- [x] Other?
    - [x] Setuptools no longer bundled with Python (#125)

I aim to get all this cleared up this week and cut a release with support on Monday, September 25, 2023, since the planned final release date for Python 3.12.0 is two weeks from today (Monday, October 2, 2023).

**Comment by Mr0grog** [comment]
Published 0.4.3a1 to PyPI, which seems to install and work well on Python 3.12.0rc2 for me. I think we can consider this good.

I’d like to take some time this weekend and try to solve #116 and #119 as well in the final release of v0.4.3 on Monday.
